config/routes.rb
Rails.application.routes.draw do

  # カード登録ルーティング
  resources :card, only: [:new, :show, :edit] do
  collection do
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


devise_scope :user do
  get 'addresses', to: 'users/registrations#new_address'
  get 'tmp_address', to: 'users/registrations#tmp_address'
  get 'edit_address', to: 'users/registrations#edit_address'
  post 'addresses', to: 'users/registrations#create_address'
  get 'sms_confirmation', to: 'users/registrations#sms_confirmation'
  get 'sms_recieved', to: 'users/registrations#sms_recieved'
  get 'register_credit_card', to: 'users/registrations#register_credit_card'
  post 'register_credit_card', to: 'users/registrations#register_credit_card'
  get 'complete', to: 'users/registrations#complete'

  # ここまで
end
  resources :mypages, only: [:show,:edit] do
    collection do
      get 'logout'
      get 'status'
    end
  end
  resources :users, only: [:index,:new, :show, :edit, :update]
  resources :addresses, only: [:new, :create]
  resources :searches, only: [:index]
  # get '/searches/detail_search', to: 'searches#detail_search'

  resources :purchase, only: [:show] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
  post "/", to: "purchase#pay"
  resources :categories, only: :index do
  end

  root "items#index"
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
      get 'show_own'
      get 'show_buyer'
    end
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user, optional: true
  validates :prefectures, :city, :address ,presence: true
  validates :postal_code,presence: true,
#            # 郵便番号(ハイフンあり7桁)
            format: { with: /\A\d{3}-\d{4}\z/, message: "はハイフンを入れて半角英数字で入力してください" }
# ユーザーログイン側はenumを使用しておりますので、こちらの記述も残しておきます
            enum prefectures:{
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  # belongs_to :customer
  # belongs_to :card
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :item, optional: true
  validates :src, :item_id, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :seller, class_name:"User", foreign_key: 'seller_id'
  belongs_to :category
  has_many :images, dependent: :destroy
  belongs_to :brand, optional: true
  accepts_nested_attributes_for :images, allow_destroy: true


  # validation
  validates :name, :description,:condition, :cover_postage, :prefectures, :shipping_date, :price, :seller_id ,:category_id,presence: true
  validates :name, length: { in: 1..40}, presence: true
  validates :description, length: { in: 1..1000}, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 299, less_than: 9999999}
  validates :category_id, numericality: { only_integer: true }
  # validates :src, presence: true

  include AASM

  aasm do
  # 状態の説明

  # 出品中(selling)

  # 出品停止中(pending)

  # 取引中(dealing)

  # 売却済み(completed)
    state :selling, :initial => true
    state :pending, :dealing, :completed


    # 出品中＝＞出品停止中

    event :stop_sales do
      transitions :from => :selling, :to => :pending
    end


    # 出品中＝＞取引中
    event :sold do
      transitions :from => :selling, :to => :dealing
    end


    # 取引中＝＞売却済み
    event :closing do
      transitions :from => :dealing, :to => :completed
    end
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  mount_uploader :avatar, ImageUploader

  # バリデーション
  validates :nickname, :first_name, :last_name, :birth_year, :birth_month, :birth_day, presence: true, on: :sign_up
  validates :password, presence: true, length: { minimum: 7 }, 
            # 英数字のみ可
            format: { with: /\A[a-z0-9]+\z/i, message: "は半角英数字７文字以上で入力してください" }, on: :sign_up
  validates :email, presence: true, 
            # 重複不可
            uniqueness: { case_sensitive: false }, 
            # 英数字のみ可,@を挟んだemailの形になっているか
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "は不正な文字が使われています。たぶん。" }
  validates :last_name_kana, :first_name_kana, presence: true, 
            # カナのみ可
            format: { with: /\A([ァ-ン]|ー)+\z/, message: "はカタカナで入力してください" }

  has_many :sns_credentials
  has_one :address
  has_many :items
  has_many :cards


  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credit_card/_info.html.haml
.credit-info
  .credit-info--header 支払い方法
  .credit-info--body
    %section
      .credit-info--body--name クレジットカード一覧
      %ul
        %li.credit-info--body--content
          = form_with url: delete_card_index_path,local: true, method: :post, id: "deleteForm" do |f|
            %figure
              %input{ type: "hidden", name: "card_id", value: "" }
              = image_tag "visa.png", width: '50', height: '30', alt: @card_brand, id: "card_image"
              = f.submit "削除する", class: "dlt-btn"
            .credit-info--body--content--number
              = "**** **** **** " + @default_card_information.last4
            .credit-info--body--content--data
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
        .credit-info--body--content--detaiil
          = link_to do
            %span 支払い方法について
            = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'liked-items__header__links--right__icon')

app/views/credit_card/index.html.haml
.payment-method
      %section.payment-method__container
        %h2.payment-method__head 支払い方法
        .payment-method__inner
          %section
            .payment-list
              %h3.payment-list__head クレジットカード一覧
            %ul.payment-list__content
          %section.add-credit-card
            .add-credit-card__content
              = link_to credit_card_path(@credit_card), class: 'submit_button', data: {"turbolinks" => false} do
                .add-credit-card__btn
                  = fa_icon 'credit-card'
                  %span<>
                  クレジットカードを追加する
          .payment-footer
            = link_to do
              %span 支払い方法について
              = fa_icon 'chevron-right'
              %span<>

app/views/detail/_comment.html.haml
%li.clearfix
  %figure
    %div
      = link_to do
        = image_tag 'brand-item.jpg', alt: 'brand-item'
    %figcaption.bold 
      = link_to do
        ニックネーム  
    = icon('fas', 'caret-down',class:"comment-mark")
  .comment-body
    .comment-body__text
      はじめまして。コメント失礼いたします。
      %br
      購入を考えているのですが、こちらの商品はお値下げ可能でしょうか？
      %br
      よろしくお願いいたします。
    .comment-body__icon
      %time.comment-body__icon__left
        = icon('far', 'clock')
        %span 10時間前
      .comment-body__icon__right
        = icon('far', 'flag')



%li.clearfix
  %figure
    %div
      = link_to do
        = image_tag 'brand-item.jpg', alt: 'brand-item'
    %figcaption.bold 
      = link_to do
        まりこ  
    = link_to "#",class:"comment-seller" do
      出品者
    = icon('fas', 'caret-down',class:"comment-mark")
  .comment-body
    .comment-body__text
      お問い合わせありがとうございます！
      %br
      3500円まででしたら可能です。
      %br
      ご検討下さいませ。
    .comment-body__icon
      %time.comment-body__icon__left
        = icon('far', 'clock')
        %span 10時間前
      .comment-body__icon__right
        = icon('far', 'flag')

app/views/detail/_itembox.html.haml
%ul.itembox-content
  %li.itembox-content__item
    .itembox-content__item__link
      = link_to do
        %figure.itembox-content__item__figure
          %figcaption.itembox-content__item__figure__caption 
            %h3.itembox-content__item__figure__caption__name
              商品名の入るところ
            .itembox-content__item__figure__caption__num
              .itembox-content__item__figure__caption__num__price ¥1,000
              .itembox-content__item__figure__caption__num__icon
                = icon('far', 'heart')
                12
          .itembox-content__item__thumnail 
          = image_tag 'brand-item.jpg', alt: 'brand-item',class: 'itembox-content__item__thumnail__image' 

  %li.itembox-content__item
    .itembox-content__item__link
      = link_to do
        %figure.itembox-content__item__figure
          %figcaption.itembox-content__item__figure__caption 
            %h3.itembox-content__item__figure__caption__name
              商品名の入るところ
            .itembox-content__item__figure__caption__num
              .itembox-content__item__figure__caption__num__price ¥1,000
              .itembox-content__item__figure__caption__num__icon
                = icon('far', 'heart',class:"gray-heart")
                12
          .itembox-content__item__thumnail 
          = image_tag 'brand-item.jpg', alt: 'brand-item',class: 'itembox-content__item__thumnail__image' 

  %li.itembox-content__item
    .itembox-content__item__link
      = link_to do
        %figure.itembox-content__item__figure
          %figcaption.itembox-content__item__figure__caption 
            %h3.itembox-content__item__figure__caption__name
              商品名の入るところ
            .itembox-content__item__figure__caption__num
              .itembox-content__item__figure__caption__num__price ¥1,000
              .itembox-content__item__figure__caption__num__icon
                = icon('far', 'heart',class:"gray-heart")
                12
          .itembox-content__item__thumnail 
          = image_tag 'brand-item.jpg', alt: 'brand-item',class: 'itembox-content__item__thumnail__image' 

app/views/layouts/show_layout/_show-bottom.html.haml
    .item-description-box
      %p.item-description-box__inner 
        = @item.description
    .item-button-box
      .item-button-box-left
        .item-button-box-left__like.item-botton
          = icon('far', 'heart')
          いいね
          ２５
        .item-button-box-left__report.item-botton
          = link_to do
            = icon('far', 'flag')
            %span 不適切な商品の報告
      .item-button-box-right
        = link_to do
          = icon('fas', 'lock')
          %span あんしん・あんぜんへの取り組み

  -# コメントボックス
  .item-detail-comment
    .comment-content
      %ul.message-items
        = render "detail/comment"
    .comment-content
      .message-form
        = form_with model:@user,local: true do |form|
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = form.text_area :nickname, class: "textarea-default"
          = form.submit "コメントする", class: "submit-detail"

  -# ナビバー
  %ul.nav-item-link
    .nav-item-link__previous
      = link_to do
        = icon('fas', 'chevron-left')
        前の商品名
    .nav-item-link__next
      = link_to do
        次の商品名
        = icon('fas', 'chevron-right')

  -# SNSロゴ
  .sns-logo-container
    %ul.sns-logo-box
      %li
        = link_to "#", class:"btn" do
          = icon('fab', 'facebook', class:'fa-3x')
      %li
        = link_to "#", class:"btn" do
          = icon('fab', 'twitter',class:'fa-3x')
      %li.hidden-item
        = link_to "#", class:"btn" do
          = icon('fab', 'line',class:'fa-3x')
      %li
        = link_to "#", class:"btn" do
          = icon('fab', 'pinterest',class:'fa-3x')

  -# ユーザーのその他出品一覧
  .other-items-in-user
    %section
      %h2.itembox-head
        = link_to "#",class:"items-in-box" do
          まりこさんのその他の出品
        = render "detail/itembox"
    %section
      %h2.itembox-head
        = link_to "#",class:"items-in-box" do
          コーチのショルダーバッグ  その他の商品
        = render "detail/itembox"

  - breadcrumb :item,@item
  = render "layouts/breadcrumbs"
= render "footer"