config/routes.rb
Rails.application.routes.draw do

  # カード登録ルーティング
  resources :card, only: [:new, :show, :edit] do
  collection do
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


devise_scope :user do
  get 'addresses', to: 'users/registrations#new_address'
  get 'tmp_address', to: 'users/registrations#tmp_address'
  get 'edit_address', to: 'users/registrations#edit_address'
  post 'addresses', to: 'users/registrations#create_address'
  get 'sms_confirmation', to: 'users/registrations#sms_confirmation'
  get 'sms_recieved', to: 'users/registrations#sms_recieved'
  get 'register_credit_card', to: 'users/registrations#register_credit_card'
  post 'register_credit_card', to: 'users/registrations#register_credit_card'
  get 'complete', to: 'users/registrations#complete'

  # ここまで
end
  resources :mypages, only: [:show,:edit] do
    collection do
      get 'logout'
      get 'status'
    end
  end
  resources :users, only: [:index,:new, :show, :edit, :update]
  resources :addresses, only: [:new, :create]
  resources :searches, only: [:index]
  # get '/searches/detail_search', to: 'searches#detail_search'

  resources :purchase, only: [:show] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
  post "/", to: "purchase#pay"
  resources :categories, only: :index do
  end

  root "items#index"
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
      get 'show_own'
      get 'show_buyer'
    end
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
    end
  end
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  require 'payjp'
  before_action :set_item, only: [:show, :pay, :done]
  before_action :set_card, only: [:pay, :done]
  before_action :anti_buy_my_own, only: [:pay, :show]
  before_action :anti_buy_sold_item, only: [:pay, :show]

  def show
    # card_idの有無で分岐
    if current_user.card_id.present?
      @card = Card.find_by(id: current_user.card_id)
      Payjp.api_key = 'sk_test_a0029dc5466705b77c5d7bab'
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
    else
      # card_idがないつまり未登録。これで購入画面侵入を防いだ。
      redirect_back(fallback_location: root_path)
      flash[:notice] = 'まずはクレジットカードの登録をしてください'
    end
  end

  def pay
    Payjp.api_key = 'sk_test_a0029dc5466705b77c5d7bab'
    Payjp::Charge.create(
    amount: @item.price,
    customer: @card.customer_id, #顧客ID
    currency: 'jpy',
  )
  redirect_to done_purchase_index_path(id:@item.id) #完了画面に移動
  end


  def done
  customer = Payjp::Customer.retrieve(@card.customer_id)
  @default_card_information = customer.cards.retrieve(@card.card_id)
  # ここでItemのbuyer_idをupdate
  @item_buyer= Item.find(params[:id])
  @item_buyer.update( buyer_id: current_user.id)
    if @item_buyer.save
      @item.sold!
    else
      redirect_to parchase_path
      flash[:delete] = "購入できませんでした"
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_card
    @card = Card.find_by(id: current_user.card_id)
  end

  def anti_buy_my_own
    @item = Item.find(params[:id])
    if @item.seller_id == current_user.id
      redirect_to root_path
      flash[:notice] = "自分で自分の買うとかないでしょ・・・"
    end
  end

  def anti_buy_sold_item
    @item = Item.find(params[:id])
    if @item.buyer_id.present?
      redirect_to root_path
      flash[:notice] = "売り切れだっつーの"
    end
  end

end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
.buy-container
  %header.buy-header
    %h1
      = link_to root_path do
        = image_tag 'fmarket_logo_red.svg'
  %main.buy-main
    %section.buy-content
      %h2.buy-content__head 購入が完了しました
      %section.buy-content__item
        .buy-content__item__inner
          .buy-item-box
            %h3.buy-item__image
              = image_tag "#{@item.images[0].src}"
            .buy-item-detail
              %p.buy-item-detail__name
                = @item.name
              %p.buy-item-detail__price
                %span
                  = @item.price
                %span.item-shipping__fee
                  円（税込）送料込み
      %section.buy-content__price
        .buy-content__price-inner
          .buy-form            
            %ul.buy-price__table
              %li.buy-price
                .buy-price__cell-label
                  支払い金額
                .buy-price__cell
                  %span.buy-pay
                    ¥
                    = @item.price  
            
            %section.buy-user__info
              .buy-content__inner
                .buy-content__container
                  %h1.payment-method__container-left
                    支払い方法
                  
                %p.buy-user-info-text
                  クレジットカード
                  %br/
                  = "**** **** **** " + @default_card_information.last4
                  %br/
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = "有効期限" + exp_month + " / " + exp_year
                
                %figure.buy-card__logo  
                  = image_tag "https://cdn-ak.f.st-hatena.com/images/fotolife/c/cardmics/20160717/20160717144815.gif", alt: "master-card", height: "20", width: "34"
            %section.buy-user__info
              .buy-content__inner
                .buy-content__container
                  %h3.l-left
                    配送先
                  
                %address.buy-user-info-text
                  %p
                    〒
                    =current_user.address.postal_code
                    %br/
                    =current_user.address.prefectures
                    =current_user.address.city
                    =current_user.address.address
                    =current_user.address.building
                    %br/
                    =current_user.first_name 
                    =current_user.last_name
            %section.buy-user__info
             
  %footer.buy-footer
    %nav
      %ul.clearfix
        %li
          = link_to root_path do 
            プライバシーポリシー
        %li
          = link_to root_path do
            Fmarket利用規約
        %li
          = link_to root_path do 
            特定商取引に関する表記
    = link_to root_path, class: "single-footer-logo" do
      = image_tag 'logo_gray.svg', alt: 'Fmarket', height: '65', width: '80'
    %p
      %small © Fmarket, Inc.

app/views/purchase/show.html.haml
.buy-container
  %header.buy-header
    %h1
      = link_to root_path do
        = image_tag 'fmarket_logo_red.svg'
  %main.buy-main
    %section.buy-content
      %h2.buy-content__head 購入内容の確認
      %section.buy-content__item
        .buy-content__item__inner
          .buy-item-box
            %h3.buy-item__image
              = image_tag "#{@item.images[0].src}"
            .buy-item-detail
              %p.buy-item-detail__name
                = @item.name
              %p.buy-item-detail__price
                %span
                  = @item.price
                %span.item-shipping__fee
                  円（税込）送料込み
      %section.buy-content__price
        .buy-content__price-inner
          .buy-form            
            %ul.buy-price__table
              %li.buy-price
                .buy-price__cell-label
                  支払い金額
                .buy-price__cell
                  %span.buy-pay
                    ¥
                    = @item.price  
            %ul.buy-point__table
              %li.user-point
                .buy-use-point
                  %input{disabled: "disabled", type: "checkbox"}/
                  %i.icon-check
                  %label ポイントを使用 (所持ポイント: P0)
            %section.buy-user__info
              .buy-content__inner
                .buy-content__container
                  %h1.payment-method__container-left
                    支払い方法
                  = link_to edit_card_path(current_user), class: "payment-method__container-right" do
                    %span
                      変更する
                %p.buy-user-info-text
                  クレジットカード
                  %br/
                  = "**** **** **** " + @default_card_information.last4
                  %br/
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = "有効期限" + exp_month + " / " + exp_year
                
                %figure.buy-card__logo  
                  = image_tag "https://cdn-ak.f.st-hatena.com/images/fotolife/c/cardmics/20160717/20160717144815.gif", alt: "master-card", height: "20", width: "34"
            %section.buy-user__info
              .buy-content__inner
                .buy-content__container
                  %h3.l-left
                    配送先
                  = link_to root_path, class: "l-right" do
                    %span
                      変更する
                %address.buy-user-info-text
                  %p
                    =current_user.address.postal_code
                    %br/
                    =current_user.address.prefectures
                    =current_user.address.city
                    =current_user.address.address
                    =current_user.address.building
                    %br/
                    =current_user.first_name 
                    =current_user.last_name
            %section.buy-user__info
              = form_tag(action: :pay, method: :post, id:@item.id) do

                %button 購入する
              
              
  %footer.buy-footer
    %nav
      %ul.clearfix
        %li
          = link_to root_path do 
            プライバシーポリシー
        %li
          = link_to root_path do
            Fmarket利用規約
        %li
          = link_to root_path do 
            特定商取引に関する表記
    = link_to root_path, class: "single-footer-logo" do
      = image_tag 'logo_gray.svg', alt: 'Fmarket', height: '65', width: '80'
    %p
      %small © Fmarket, Inc.