config/routes.rb
Rails.application.routes.draw do

  # カード登録ルーティング
  resources :card, only: [:new, :show, :edit] do
  collection do
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


devise_scope :user do
  get 'addresses', to: 'users/registrations#new_address'
  get 'tmp_address', to: 'users/registrations#tmp_address'
  get 'edit_address', to: 'users/registrations#edit_address'
  post 'addresses', to: 'users/registrations#create_address'
  get 'sms_confirmation', to: 'users/registrations#sms_confirmation'
  get 'sms_recieved', to: 'users/registrations#sms_recieved'
  get 'register_credit_card', to: 'users/registrations#register_credit_card'
  post 'register_credit_card', to: 'users/registrations#register_credit_card'
  get 'complete', to: 'users/registrations#complete'

  # ここまで
end
  resources :mypages, only: [:show,:edit] do
    collection do
      get 'logout'
      get 'status'
    end
  end
  resources :users, only: [:index,:new, :show, :edit, :update]
  resources :addresses, only: [:new, :create]
  resources :searches, only: [:index]
  # get '/searches/detail_search', to: 'searches#detail_search'

  resources :purchase, only: [:show] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
  post "/", to: "purchase#pay"
  resources :categories, only: :index do
  end

  root "items#index"
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
      get 'show_own'
      get 'show_buyer'
    end
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  end  

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search-zone.html.haml
.drop_downs
  %h3.large-word 詳細検索

  = search_form_for@search,url: searches_path do |f|
    .form_normal
      %i.fas.fa-plus
      キーワードを追加する
      = f.search_field :name_cont_any, class: "input-default", placeholder: "#{@items.name}"
    .form__slot
      %i.fas.fa-coins
      = f.label :karioki, "価格", class: "label-font"
      = f.search_field :price_gteq,class: 'search__box-half', placeholder: "¥ Min"
      %span ~
      = f.search_field :price_lteq,class: 'search__box-half', placeholder: "¥ Max"
    .form__slot
      - rank = {全部: 0, 新品、未使用: 1, 未使用に近い: 2, 目立った傷や汚れなし: 3, やや汚れや傷あり: 4, 傷や汚れあり: 5, 全体的に状態が悪い: 6}
      %i.fas.fa-star
      = f.label :condition_in, '商品の状態', class: "label-font"
      %p
      - rank.each do |key, value|
        .checkbox_default
          = f.check_box :karioki, {checked: false, multiple: true, class: "checkbox_space"}
          = key
    .form__slot
    .button-box
      = f.button "クリア", type: :reset, class: "button-clear"
      = f.submit "完了", class: "button-submit"

app/views/searches/_search_item.html.haml
.category-items
  .category-items__item
    -if @keyword.blank?
      - @items.each do |item|
        .category-items__item__link
          = link_to item_path(item.id) do
            %figure.category-items__item__figure
              .category-items__item__thumbnail
                .category-items__item__thumbnail__price{aria: "", label: ""} 
                  = "¥#{item.price}"
                = image_tag "#{item.images[0].src}", alt: 'category-item',class: 'category-items__item__thumbnail__image'
                %figcaption.category-items__item__figure__caption 
                  = item.name
    -else
      -if @items.present? 
        - @exist_items.each do |exist_item|
          .category-items__item__link
            = link_to item_path(exist_item.id) do
              %figure.category-items__item__figure
                .category-items__item__thumbnail
                  .category-items__item__thumbnail__price{aria: "", label: ""} 
                    = "¥#{exist_item.price}"
                  = image_tag "#{exist_item.images[0].src}", alt: 'category-item',class: 'category-items__item__thumbnail__image'
                  %figcaption.category-items__item__figure__caption 
                    = exist_item.name
      -else
        = @not_found

app/views/searches/detail_search.html.haml
-# = render 'items/header'

-# .search-container
-#   .search
-#     .search-left
-#       = render 'search-zone'
-#     .search-right
-#       %section.items-box-container
-#         %h2.search-result-head
-#           =params[:search]
-#           %span.search-result-head-text
-#           の検索結果
-#         .search-result-number
-#           ="1-#{@items.count}件表示"
-#         .items-box-content
-#           = render "search_item"

-# = render 'items/footer'

app/views/searches/index.html.haml
-if user_signed_in?
  =render "items/header"
-else
  =render "items/header-unlogin"
.search
  .search-container
    .search-left
      = render 'search-zone'
    .search-right
      %section.items-box-container
        -if @search.present?
          %h2.search-result-head
          - @items.each do |item|
            = item.name
            %span.search-result-head-text
              の検索結果
          .search-result-number
            ="1-#{@items.count}件表示"
        -else
          %h2.search-result-nil
            検索結果
          .search-result-number
            ="1-#{@items.count}件表示"
        .items-box-content
          = render "categories/search"
= render 'items/footer'