config/routes.rb
Rails.application.routes.draw do

  # カード登録ルーティング
  resources :card, only: [:new, :show, :edit] do
  collection do
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


devise_scope :user do
  get 'addresses', to: 'users/registrations#new_address'
  get 'tmp_address', to: 'users/registrations#tmp_address'
  get 'edit_address', to: 'users/registrations#edit_address'
  post 'addresses', to: 'users/registrations#create_address'
  get 'sms_confirmation', to: 'users/registrations#sms_confirmation'
  get 'sms_recieved', to: 'users/registrations#sms_recieved'
  get 'register_credit_card', to: 'users/registrations#register_credit_card'
  post 'register_credit_card', to: 'users/registrations#register_credit_card'
  get 'complete', to: 'users/registrations#complete'

  # ここまで
end
  resources :mypages, only: [:show,:edit] do
    collection do
      get 'logout'
      get 'status'
    end
  end
  resources :users, only: [:index,:new, :show, :edit, :update]
  resources :addresses, only: [:new, :create]
  resources :searches, only: [:index]
  # get '/searches/detail_search', to: 'searches#detail_search'

  resources :purchase, only: [:show] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
  post "/", to: "purchase#pay"
  resources :categories, only: :index do
  end

  root "items#index"
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
      get 'show_own'
      get 'show_buyer'
    end
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'image', defaults: { format: 'json' }
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :seller, class_name:"User", foreign_key: 'seller_id'
  belongs_to :category
  has_many :images, dependent: :destroy
  belongs_to :brand, optional: true
  accepts_nested_attributes_for :images, allow_destroy: true


  # validation
  validates :name, :description,:condition, :cover_postage, :prefectures, :shipping_date, :price, :seller_id ,:category_id,presence: true
  validates :name, length: { in: 1..40}, presence: true
  validates :description, length: { in: 1..1000}, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 299, less_than: 9999999}
  validates :category_id, numericality: { only_integer: true }
  # validates :src, presence: true

  include AASM

  aasm do
  # 状態の説明

  # 出品中(selling)

  # 出品停止中(pending)

  # 取引中(dealing)

  # 売却済み(completed)
    state :selling, :initial => true
    state :pending, :dealing, :completed


    # 出品中＝＞出品停止中

    event :stop_sales do
      transitions :from => :selling, :to => :pending
    end


    # 出品中＝＞取引中
    event :sold do
      transitions :from => :selling, :to => :dealing
    end


    # 取引中＝＞売却済み
    event :closing do
      transitions :from => :dealing, :to => :completed
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :show_buyer]
  before_action :set_item, only: [:update, :edit, :show, :destroy]
  before_action :set_category, only: [:new,:index,:show]
  before_action :set_ransack, only: [:index,:show]

  
  def index
    @items= Item.includes(:images).order('created_at DESC') 
    @ladies = Item.where(category_id:14..211).order("created_at DESC").limit(10)
    @men = Item.where(category_id:212..356).order("created_at DESC").limit(10)
    @electronics = Item.where(category: "家電・スマホ・カメラ").order("created_at DESC").limit(10)
    @toys= Item.where(category: "おもちゃ・ホビー・グッズ").order("created_at DESC").limit(10)
    @channel = Item.where(brand_id: 1).order("created_at DESC").limit(10)
    @louisvuitton = Item.where(brand_id: 2).order("created_at DESC").limit(10)
    @supreme= Item.where(brand_id: 3).order("created_at DESC").limit(10)
    @nike= Item.where(brand_id: 4).order("created_at DESC").limit(10)
  end

  def new
    if user_signed_in?
      @item = Item.new
      @item.images.new
      @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")

      #データベースから、親カテゴリーのみ抽出し、配列化
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    else
      redirect_to root_path
    end
  end

    # 以下全て、formatはjsonのみ
    # 親カテゴリーが選択された後に動くアクション
  def category_children
      #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
      @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def category_grandchildren
  #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
      @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  def create
    @item = Item.new(item_params)
    @item.update(price: params[:price], profit_price: params[:profit_price], margin_price: params[:margin_price])
    brand = Brand.find_by(name: params[:item][:brand_id])
    if brand.present?
      @item.update(brand_id: brand.id)
    else
    new_brand = Brand.new(name: params[:item][:brand_id])
      if Brand.where.not(name: new_brand.name)
        unless new_brand.name.empty?
          new_brand.save
          @item.update(brand_id: new_brand.id)
        end
      else
      render :new
      flash[:alert] = 'ブランドの登録に失敗しました'
      end
    end
    if @item.valid? && params[:item_images].present?
      @item.save
      params[:item_images][:image].each do |image|
        @item.images.create(src: image, item_id: @item.id)
      end
      redirect_to root_path, notice: '出品完了しました'
    else
      render :new
      flash[:alert] = '出品に失敗しました。必須項目を確認してください。'
    end
  end


  def edit
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    gon.item = @item
    gon.images = @item.images
    

    require 'base64'
    require 'aws-sdk'

    gon.images_binary_datas = []

    if Rails.env.production?
      client = Aws::S3::Client.new(
      region: 'ap-northeast-1',
      access_key_id: Rails.application.credentials.aws[:access_key_id],
      secret_access_key: Rails.application.credentials.aws[:secret_access_key],
      )
      @item.images.each do |image|
        binary_data = client.get_object(bucket: 'freemarketsample60a', key: image.src.file.path).body.read
        gon.images_binary_datas << Base64.strict_encode64(binary_data)
      end
    else
      @item.images.each do |image|
        binary_data = File.read(image.src.file.file)
        gon.images_binary_datas << Base64.strict_encode64(binary_data)
      end
    end
  end

  
  def update
    # 登録済画像のidの配列を生成
    ids = @item.images.map{|image| image.id }
  
    # 登録済画像のうち、編集後もまだ残っている画像のidの配列を生成(文字列から数値に変換)
    exist_ids = registered_image_params[:ids].map(&:to_i)
    
    # 登録済画像が残っていない場合(配列に０が格納されている)、配列を空にする
    exist_ids.clear if exist_ids[0] == 0
    
    if (exist_ids.length != 0 || new_image_params[:images][0] != " ") && @item.update(item_params)
      @item.update(price: params[:price], profit_price: params[:profit_price], margin_price: params[:margin_price])
      # 登録済画像のうち削除ボタンをおした画像を削除
      unless ids.length == exist_ids.length
      # 削除する画像のidの配列を生成
        delete_ids = ids - exist_ids
        delete_ids.each do |id|
          @item.images.find(id).destroy
        end
      end

      # 新規登録画像があればcreate
      unless new_image_params[:images][0] == " "
        new_image_params[:images].each do |image|
          @item.images.create(src: image, item_id: @item.id)
        end
      end

      redirect_to item_path(@item), data: {turbolinks: false}
      flash[:notice] = '編集が完了しました'

    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = '未入力項目があります'
    end

  end

  def show
    if user_signed_in?
      if current_user.id == @item.seller.id
        render :show_own
      else
        render :show_buyer
      end
    elsif @item.buyer_id.present?
      render :show_buyer
    else
      render :show_buyer
    end
  end

  def show_own
  end

  def show_buyer
  end



  def destroy
    if user_signed_in?
      @item.destroy
      redirect_to root_path
      flash[:delete] = "商品を削除しました"
    else
      redirect_back(fallback_location: item_path)
      flash[:delete] = "削除に失敗しました"
    end
  end

  def image
    @images = Item.find(params[:item_id]).src
  end


  private

  def item_params
    params.require(:item).permit(
      :name, 
      :description, 
      :condition, 
      :cover_postage, 
      :prefectures, 
      :shipping_date, 
      :price, 
      :margin_price, 
      :profit_price, 
      :seller_id,
      :brand_id,
      :category_id, 
      :image_id,
      images_attributes: [:src,:id])
      .merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
    @grandchild = Category.find(@item[:category_id])
    @child = @grandchild.parent
    @parent = @child.parent
    end

  def registered_image_params
    params.require(:registered_images_ids).permit({ids: []})
  end

  def new_image_params
    params.require(:new_images).permit({images: []})
  end

  def set_category
    @parents = Category.all.order("id ASC").limit(13)
  end

  def set_ransack
    @search = Item.ransack(params[:q])
    @items = @search.result
  end



end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_header-unlogin.html.haml
%header.header
  .header-wrapper
    .toppage__header
      .toppage__header-contents
        = link_to image_tag("_c_choju47_0031_s64_choju47_0031_11.png",width:"40",height:"36"), root_path,{class:'toppage__header-contents--freemarket-logo'}
        気まぐれカエルのスーパーマーケット
      .toppage__header-search
        = search_form_for @search,url: searches_path do |f|
          = f.search_field :name_cont,class:'header-search-form',placeholder: '何かお探しですか？'
          = button_tag type:'submit',class:'header-search-btn' do
            = image_tag"search-solid.svg",class: 'header-search-btn'

    .toppage__footer
      %nav.toppage__footer-nav
        %ul.toppage__footer-nav-category
          %h2
            = link_to categories_path do
              = icon('fas', 'list-ul lg', alt: 'nav-icon',
              class: 'nav-icon')
              %span カテゴリーから探す
            .category-down-list
              = render partial: "categories/category"

        %ul.toppage__footer-nav-brand
          %h2
            = link_to root_path do
              = icon('fas', 'tag lg', alt: 'tag-icon',
              class: 'nav-icon')
              %span ブランドから探す
              -# burandの記述がまだなのでコメントアウト
              -# = render partial: "brand"
      .toppage__footer-contents
        .toppage__footer-contents-wrapper
          .toppage__footer-contents--new-register-btn
            = link_to '新規会員登録', new_user_path 
          .toppage__footer-contents--user-login-btn
            = link_to 'ログイン', user_session_path

app/views/items/_header.html.haml
%header.header
  .header-wrapper
    .toppage__header
      .toppage__header-contents
        = link_to root_path do
          = image_tag 'fmarket_logo_red.svg', alt: 'freemarket-logo',
          class: 'toppage__header-contents--freemarket-logo'

      .toppage__header-search

        = search_form_for@search,url: searches_path do |f|
          = f.search_field :name_cont,class:'header-search-form',placeholder: '何かお探しですか？'
          = button_tag type:'submit',class:'header-search-btn' do
            = image_tag"search-solid.svg",class: 'header-search-btn'

          
    .toppage__footer
      %nav.toppage__footer-nav
        %ul.toppage__footer-nav-category
          %h2
            = link_to categories_path do
              = icon('fas', 'list-ul lg', alt: 'nav-icon',
              class: 'nav-icon')
              %span カテゴリーから探す
            .category-down-list
              = render partial: "categories/category"
        %ul.toppage__footer-nav-brand
          %h2
            = link_to root_path do
              = icon('fas', 'tag lg', alt: 'tag-icon',
              class: 'nav-icon')
              %span ブランドから探す
              -# burandの記述がまだなのでコメントアウト
              -# = render partial: "brand"
      .toppage__footer-contents
        .toppage__footer-contents-wrapper
          
          %ul.toppage__footer-login-contents
            %li.toppage__footer-login-content
              = link_to root_path do
                = icon('far', 'heart ', alt: 'heart-icon',
                class: 'toppage__footer-login-content--heart-icon')
                %span いいね！一覧
            %li.toppage__footer-login-content--notice
              = link_to root_path do
                = icon('far', 'bell', alt: 'bell-icon',
                class: 'toppage__footer-login-content--bell-icon')
                %span お知らせ
                .toppage__footer-login-content--notice-count
                  99+
            %li.toppage__footer-login-content--todo
              = link_to root_path do
                = icon('fas', 'check', alt: 'bell-icon',class: 'toppage__footer-login-content--check-icon')
                %span やることリスト

            %li.toppage__footer-login-content--mypage
              = link_to "/mypages/:id" do
                = image_tag 'logo_gray.svg', alt: 'mypage-logo',class: 'toppage__footer-login-content--mypage-header-user-icon'
                %span マイページ
            .toppage__footer-login-content--mypage-box
              .toppage__footer-login-content--mypage-box-content
                

app/views/items/index.html.haml
-if user_signed_in?
  =render "header"
-else
  =render "header-unlogin"
.main
  = render "layouts/topview"
  .liked-items
    .liked-items__header
      %h3.liked-items__header__title いいね！した商品
      .liked-items__header__links
        = link_to "すべてみる", "#", class: "liked-items__header__links--left" 
        .liked-items__header__links--right
          = link_to do
            = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'liked-items__header__links--right__icon')
    %ul.liked-items__sliders
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
      %li.liked-items__slider__item
        .liked-items__slider__item__link
          = link_to do
            %figure.liked-items__slider__item__figure
              .liked-items__slider__item__thumbnail
                %span.liked-items__slider__item__thumbnail__price ￥1000
                = image_tag 'liked-item.jpg', alt: 'liked-item',
                class: 'liked-items__slider__item__thumbnail__image'            
  .popular-categories
    %h2.popular-categories__title 人気のカテゴリー
    %ul.popular-categories__list
      %li.popular-categories__list__category
        = link_to "レディース", "#category__ladies", class: "popular-categories__list__category__link" 
      %li.popular-categories__list__category
        = link_to "メンズ", "#category__mens", class: "popular-categories__list__category__link" 
      %li.popular-categories__list__category
        = link_to "家電・スマホ・カメラ", "#category__electronics", class: "popular-categories__list__category__link" 
      %li.popular-categories__list__category
        = link_to "おもちゃ・ホビー・グッズ", "##category__toys", class: "popular-categories__list__category__link" 
  .category-boxes
    .category-boxes__box
      .category-boxes__box__heading
        %h3.category-boxes__box__heading__title
          %a#category__ladies レディース新着アイテム
        .category-boxes__box__heading__links
          = link_to "もっとみる", "#", class: "category-boxes__box__heading__links--left" 
          .category-boxes__box__heading__links--right
          = link_to do
            = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'category-boxes__box__heading__links--right__icon')
      = render partial: "categories/ladies"
  .category-boxes
    .category-boxes__box
      .category-boxes__box__heading
        %h3.category-boxes__box__heading__title
          %a#category__ladies メンズ新着アイテム
        .category-boxes__box__heading__links
          = link_to "もっとみる", "#", class: "category-boxes__box__heading__links--left" 
          .category-boxes__box__heading__links--right
          = link_to do
            = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'category-boxes__box__heading__links--right__icon')
      = render "categories/men"

  .popular-brand
    %h2.popular-brand__title 人気のブランド
    %ul.popular-brand__list
      %li.popular-brand__list__brand
        = link_to "シャネル", "#brand__channel", class: "popular-brand__list__brand__link" 
      %li.popular-brand__list__brand
        = link_to "ルイヴィトン", "#brand__louisvuitton", class: "popular-brand__list__brand__link" 
      %li.popular-brand__list__brand
        = link_to "シュプリーム", "#brand__supreme", class: "popular-brand__list__brand__link" 
      %li.popular-brand__list__brand
        = link_to "ナイキ", "#brand__nike", class: "popular-brand__list__brand__link" 
  
  .category-boxes  
    .category-boxes__box
      .category-boxes__box__heading
        %h3.category-boxes__box__heading__title
          %a#category__ladies シャネル新着アイテム
        .category-boxes__box__heading__links
          = link_to "もっとみる", "#", class: "category-boxes__box__heading__links--left" 
          .category-boxes__box__heading__links--right
          = link_to do
            = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'category-boxes__box__heading__links--right__icon')
      = render "channel"

      .category-boxes__box
        .category-boxes__box__heading
          %h3.category-boxes__box__heading__title
            %a#category__ladies ルイヴィトン新着アイテム
          .category-boxes__box__heading__links
            = link_to "もっとみる", "#", class: "category-boxes__box__heading__links--left" 
            .category-boxes__box__heading__links--right
            = link_to do
              = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'category-boxes__box__heading__links--right__icon')
        = render "louisvuitton"
    
      .category-boxes__box
        .category-boxes__box__heading
          %h3.category-boxes__box__heading__title
            %a#category__ladies シュプリーム新着アイテム
          .category-boxes__box__heading__links
            = link_to "もっとみる", "#", class: "category-boxes__box__heading__links--left" 
            .category-boxes__box__heading__links--right
            = link_to do
              = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'category-boxes__box__heading__links--right__icon')
        = render "supreme"

      .category-boxes__box
        .category-boxes__box__heading
          %h3.category-boxes__box__heading__title
            %a#category__ladies ナイキ新着アイテム
          .category-boxes__box__heading__links
            = link_to "もっとみる", "#", class: "category-boxes__box__heading__links--left" 
            .category-boxes__box__heading__links--right
            = link_to do
              = icon('fas', 'chevron-right', alt: 'chevron-right',class: 'category-boxes__box__heading__links--right__icon')
        = render "nike"

  .selling-item-box
    = link_to new_item_path, class: "selling-item-box__link" do
      .selling-item-box__contents
        .selling-item-box__contents__letter 出品
        = icon('fas', 'camera', alt: 'camera',class: 'selling-item-box__contents__camera')

  .contents

= render"footer"

app/views/items/show.html.haml
-# showを分岐させましたので、このファイルは読まれません。


-# -if user_signed_in?
-#   =render "header"
-# -else
-#   =render "header-unlogin"
-# .item-detail-first-container
-#   -# アイテム詳細ボックス
-#   %section.item-box-container
-#     %h1.item-name-box 
-#       = @item.name
-#     .item-main-box
-#       -if @item.buyer_id.present? 
-#         .items__sold
-#           .items__sold__inner
-#             SOLD
-#       .box-photo
-#         .box-photo__photo
-#           - @item.images.each_with_index do |image, i|
-#             = image_tag "#{image.src}"
        
-#       %table.box__detail-table
-#         %tbody
-#           %tr
-#             %th
-#               出品者
-#             %td
-#               = link_to do
-#                 = @item.seller.nickname
-#               %div
-#                 .user-ratings
-#                   %i.icon-good
-#                     = icon('fas', 'kiss-wink-heart')
-#                   %span
-#                   11
-#                 .user-ratings
-#                   %i.icon-nomal
-#                     = icon('fas', 'meh')
-#                   %span
-#                   14
-#                 .user-ratings
-#                   %i.icon-bad 
-#                     = icon('fas', 'dizzy')
-#                   %span
-#                   1
-#           %tr
-#             %th
-#               カテゴリ
-#             %td
-#               = link_to do
-#                 = @parent.name
-#               = link_to do
-#                 .sub-category
-#                   = icon('fas', 'chevron-right')
-#                   = @child.name
-#               = link_to do
-#                 .sub-sub-category
-#                   = icon('fas', 'chevron-right')
-#                   = @grandchild.name
-#           %tr
-#             %th
-#               ブランド
-#             %td
-#               = link_to do
-#                 コーチ
-#           %tr
-#             %th
-#               商品の状態
-#             %td
-#               = @item.condition
-#           %tr
-#             %th
-#               配送料の負担
-#             %td
-#               = @item.cover_postage
-#           %tr
-#             %th
-#               配送の方法
-#             %td
-#               らくらくFmart便
-#           %tr
-#             %th
-#               配送元地域
-#             %td
-#               = link_to do
-#                 = @item.prefectures
-#           %tr
-#             %th
-#               発送日の目安
-#             %td
-#               = @item.shipping_date
-#     .item-price-box
-#       %span.item-price-box.bold
-#         = "¥#{@item.price}"
-#       %span.item-price-box.tax
-#         (税込)
-#       %span.item-price-box.fee
-#         送料込み
-#     .itms-buybox
-#     -# -else
-#     -#   = link_to 'ユーザー登録してね',root_path,class: 'item-buy-button '
-#     - if user_signed_in? && current_user.id == @item.seller_id
-#       = link_to "編集する", edit_item_path(@item.id),class:"item-sold-button"
-#       .t_delete
-#         この商品を削除する
-#       .t_overlay
-#       .t_modalWindow
-#         .t_modalWindow__content
-#           %p
-#           %span 確認 
-#           %p 削除すると二度と復活できません。
-#           %p 削除する代わりに停止することもできます。
-#           %br
-#           %p 本当に削除しますか？
-#         .t_modalWindow__buttons
-#           .t_modalWindow__buttons__btn--cxl
-#             キャンセル
-#           .t_modalWindow__buttons__btn--cxl
-#             = link_to "この商品を削除する",item_path(@item.id), method: :delete, class: "t_modalWindow__buttons__btn"
-#     - elsif @item.buyer_id.present?  
-#       = link_to '売り切れました','#',class: 'item-sold-button '
-#     -else 
-#       = link_to '購入画面に進む', purchase_path,class: 'item-buy-button '
-#     .item-description-box
-#       %p.item-description-box__inner 
-#         = @item.description
-#     .item-button-box
-#       .item-button-box-left
-#         .item-button-box-left__like.item-botton
-#           = icon('far', 'heart')
-#           いいね
-#           ２５
-#         .item-button-box-left__report.item-botton
-#           = link_to do
-#             = icon('far', 'flag')
-#             %span 不適切な商品の報告
-#       .item-button-box-right
-#         = link_to do
-#           = icon('fas', 'lock')
-#           %span あんしん・あんぜんへの取り組み

-#   -# コメントボックス
-#   .item-detail-comment
-#     .comment-content
-#       %ul.message-items
-#         = render "detail/comment"
-#     .comment-content
-#       .message-form
-#         = form_with model:@user,local: true do |form|
-#           %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
-#           = form.text_area :nickname, class: "textarea-default"
-#           = form.submit "コメントする", class: "submit-detail"

-#   -# ナビバー
-#   %ul.nav-item-link
-#     .nav-item-link__previous
-#       = link_to do
-#         = icon('fas', 'chevron-left')
-#         前の商品名
-#     .nav-item-link__next
-#       = link_to do
-#         次の商品名
-#         = icon('fas', 'chevron-right')

-#   -# SNSロゴ
-#   .sns-logo-container
-#     %ul.sns-logo-box
-#       %li
-#         = link_to "#", class:"btn" do
-#           = icon('fab', 'facebook', class:'fa-3x')
-#       %li
-#         = link_to "#", class:"btn" do
-#           = icon('fab', 'twitter',class:'fa-3x')
-#       %li.hidden-item
-#         = link_to "#", class:"btn" do
-#           = icon('fab', 'line',class:'fa-3x')
-#       %li
-#         = link_to "#", class:"btn" do
-#           = icon('fab', 'pinterest',class:'fa-3x')

-#   -# ユーザーのその他出品一覧
-#   .other-items-in-user
-#     %section
-#       %h2.itembox-head
-#         = link_to "#",class:"items-in-box" do
-#           まりこさんのその他の出品
-#         = render "detail/itembox"
-#     %section
-#       %h2.itembox-head
-#         = link_to "#",class:"items-in-box" do
-#           コーチのショルダーバッグ  その他の商品
-#         = render "detail/itembox"

-#   - breadcrumb :item,@item
-#   = render "layouts/breadcrumbs"
-# = render "footer"